# Generated by Django 3.2.7 on 2021-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
