# Generated by Django 3.2.7 on 2021-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210926_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='Person/mainImg', verbose_name='Image principale'),
        ),
    ]
