# Generated by Django 3.2.7 on 2021-10-02 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du service')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('photoService', models.ImageField(blank=True, null=True, upload_to='Image', verbose_name='Photo service')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Liste des services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SaveArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Titre de l'archive")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fileToSave', models.FileField(blank=True, null=True, upload_to='Files/', verbose_name='Fichiers')),
                ('fileUpload', models.TextField(blank=True, null=True)),
                ('dateToSave', models.CharField(blank=True, default=datetime.date(2021, 10, 2), max_length=25, null=True, verbose_name="Date d'enregistrement")),
                ('timeToSave', models.CharField(blank=True, default=datetime.time(23, 3, 37, 597438), max_length=25, null=True, verbose_name="Heure d'enregistrement")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Liste des archives',
            },
        ),
    ]
